let topics=["Development","Marketing","Personal Development","Design"];//,"Teaching & Academics","Photography","Finance & Accounting Courses"];
let subtopics=[["Web Development","Mobile Apps","Programming Languages"],["Digital Marketing","Social Media marketing","Branding"],["Personal Transformation","Productivity","Leadership"],["Graphics Design","Web Design","User Experience","Game Design","3D & Animation","Architectural Design"]];//"Leadership",/*"Career Development","Parenting & Relationships","Happiness"*/],["Humanities","Engineering","Math"/*,"Science","Online Education","Test Prep"*/],["Digital Photography","Photography Fundamentals","Portraits","Commercial Photography","Video design","Photography tools"],["Accounting & Bookkeeping","Compliance","Crypto currency & Blockchain","Economic","Finance"]]
let sec11=[{name: "The Complete Web Developer Course 2.0" , img: "111.jpg" , rating: 4,prop:"Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!"},{name: "Angular - The Complete Guide (2020 Edition)" , img: "112.jpg" , rating:5 ,prop: "Master Angular 10 (formerly 'Angular 2') and build awesome, reactive web apps with the successor of Angular.js"},{name: "The Web Developer Bootcamp" , img: "113.jpg" , rating:4 ,prop: "The only course you need to learn web development - HTML, CSS, JS, Node, and More!"},{name: "Modern React with Redux [2020 Update]" , img: "114.jpg" , rating:5,prop:"" },{name: "Vue JS 2 - The Complete Guide (incl. Vue Router & Vuex)" , img: "115.jpg" , rating:4 ,prop: "Vue.js is an awesome JavaScript Framework for building Frontend Applications! VueJS mixes the Best of Angular + React!"}];
let sec12=[{name: "The Complete Android N Developer Course" , img: "121.jpg" , rating: 4,prop:"Learn Android App Development with Android 7 Nougat by building real apps including Uber, Whatsapp and Instagram!"},{name: "iOS 10 & Swift 3: From Beginner to Paid Professional™" , img: "122.jpg" , rating:5 ,prop: "The most comprehensive course on iOS development - become a master of app development"},{name: "Flutter & Dart - The Complete Guide [2020 Edition]" , img: "123.jpg" , rating:4 ,prop: "A Complete Guide to the Flutter SDK & Flutter Framework for building native iOS and Android apps"},{name: "Ionic - Build iOS, Android & Web Apps with Ionic & Angular" , img: "124.jpg" , rating:5 ,prop: "Build Native iOS & Android as well as Progressive Web Apps with Angular, Capacitor and the Ionic Framework (Ionic 4+)."},{name: "Xamarin Forms: Build Native Cross-platform Apps with C#" , img: "125.jpg" , rating:4 ,prop: "Learn to build native mobile apps for Android, iOS and Windows using your existing C# skills Bestseller"}];
let sec13=[{name: "2020 Complete Python Bootcamp: From Zero to Hero in Python" , img: "131.jpg" , rating: 4,prop:"Learn Python like a Professional! Start from the basics and go all the way to creating your own applications and games! "},{name: "Java Programming Masterclass for Software Developers" , img: "132.jpg" , rating:5 ,prop: "Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification"},{name: "React - The Complete Guide (incl Hooks, React Router, Redux)" , img: "133.jpg" , rating:4 ,prop: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!"},{name: "Learn Python Programming Masterclass" , img: "134.jpg" , rating:5 ,prop: "This Python For Beginners Course Teaches You The Python Language Fast. Includes Python Online Training With Python 3"},{name: "The Python Mega Course: Build 10 Real World Applications" , img: "135.jpg" , rating:4 ,prop: "A complete Python course for both beginners and intermediates! Master Python 3 by making 10 amazing Python apps."}];
//let sec14=[{name: "" , img: "141.jpg" , rating: 4,prop:" "},{name: "" , img: "142.jpg" , rating:5 ,prop: ""},{name: "" , img: "143.jpg" , rating:4 ,prop: ""},{name: "" , img: "144.jpg" , rating:5 ,prop: ""},{name: "" , img: "145.jpg" , rating:4 ,prop: ""}];
//let sec15=[{name: "" , img: "151.jpg" , rating: 4,prop:" "},{name: "" , img: "152.jpg" , rating:5 ,prop: ""},{name: "" , img: "153.jpg" , rating:4 ,prop: ""},{name: "" , img: "154.jpg" , rating:5 ,prop: ""},{name: "" , img: "155.jpg" , rating:4 ,prop: ""}];
//let sec16=[{name: "" , img: "161.jpg" , rating: 4,prop:" "},{name: "" , img: "162.jpg" , rating:5 ,prop: ""},{name: "" , img: "163.jpg" , rating:4 ,prop: ""},{name: "" , img: "164.jpg" , rating:5 ,prop: ""},{name: "" , img: "165.jpg" , rating:4 ,prop: ""}];
let sec21=[{name: "The Complete Digital Marketing Course - 12 Courses in 1" , img: "211.jpg" , rating: 4,prop:"Master Digital Marketing: Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More!"},{name: "Digital Marketing Certification: Master Digital Marketing" , img: "212.jpg" , rating:5 ,prop: "Join Over 100.000 Students Who Have Already Learned All The Secrets of Digital Marketing. Be a Digital Marketing Expert!"},{name: "Digital Marketing Masterclass:Get Your First 1,000 Customers" , img: "213.jpg" , rating:4 ,prop: "How to acquire your first 1,000 customers using Social media, Content & Video Marketing, PR, SEO, SEM, FB, InstaG &more"},{name: "VIP Digital Marketing Master Course : 31 Courses in 1" , img: "214.jpg" , rating:5 ,prop: "Digital Marketing Course : Instagram marketing, Facebook, SEO, Google ads, Youtube, Email & Mailchimp, Wordpress & ..."},{name: "Digital Advertising & Marketing 101: Take The Complete Guide" , img: "215.jpg" , rating:4 ,prop: "Top Digital Marketing Course | Facebook Ads, Google/YouTube, Display/Video & more|Grow your career (German/Portuguese)"}];
let sec22=[{name: "Facebook Ads & Facebook Marketing MASTERY 2020 | Coursenvy ®" , img: "221.jpg" , rating: 4,prop:"Facebook Marketing from beginner to advanced! Join 100,000+ students who MASTERED Facebook and are Facebook Ads experts! "},{name: "Instagram Marketing 2020: Complete Guide To Instagram Growth" , img: "222.jpg" , rating:5 ,prop: "Attract Hyper-Targeted Instagram Followers, Convert Followers to Paying Customers, & Expand your Brand Using Instagram"},{name: "Social Media Marketing MASTERY | Learn Ads on 10+ Platforms" , img: "223.jpg" , rating:4 ,prop: "MASTER online marketing on Twitter, Pinterest, Instagram, YouTube, Facebook, Google and more ad platforms! Coursenvy ®"},{name: "Instagram Marketing 2020: Hashtags, Live, Stories, Ads &more" , img: "224.jpg" , rating:5 ,prop: "Watch me take an account from an idea to 40k followers in 4 months. 14 hours instruction, 8 hours of BTS videos"},{name: "Social Media Management - The Complete 2019 Manager Bootcamp" , img: "225.jpg" , rating:4 ,prop: "Become a freelance social media manager | Start a management business | Work from anywhere | Achieve financial freedom"}];
let sec23=[{name: "Business Branding: The Complete Course Part 1 - Expression" , img: "231.jpg" , rating: 4,prop:"Express Your Business Brand With Advanced Messaging And Storytelling Frameworks"},{name: "Business Branding: The Complete Course Part 2 - Expression" , img: "232.jpg" , rating:5 ,prop: "Express Your Business Brand With Advanced Messaging And Storytelling Frameworks"},{name: "Business Branding Branding: How to Brand Yourself and Your Business" , img: "233.jpg" , rating:4 ,prop: "Create a Unique and Compelling Brand That Sets You Apart from Everyone Else Who Does What You Do"},{name: "The Climb: 6 Steps to a Powerful Personal Brand" , img: "234.jpg" , rating:5 ,prop: "Grow Your Following, Boost Your Career, and Skyrocket Your Income with a Powerful Personal Brand"},{name: "Business Branding - Build An Extraordinary Brand On A Budget" , img: "235.jpg" , rating:4 ,prop: "Effortlessly Craft A Brand Your Audience CRAVES Starting TODAY, WITHOUT ANY Marketing Experience or Budget Step-by-Step."}];
//let sec24=[{name: "" , img: "241.jpg" , rating: 4,prop:" "},{name: "" , img: "242.jpg" , rating:5 ,prop: ""},{name: "" , img: "243.jpg" , rating:4 ,prop: ""},{name: "" , img: "244.jpg" , rating:5 ,prop: ""},{name: "" , img: "245.jpg" , rating:4 ,prop: ""}];
//let sec25=[{name: "" , img: "251.jpg" , rating: 4,prop:" "},{name: "" , img: "252.jpg" , rating:5 ,prop: ""},{name: "" , img: "253.jpg" , rating:4 ,prop: ""},{name: "" , img: "254.jpg" , rating:5 ,prop: ""},{name: "" , img: "255.jpg" , rating:4 ,prop: ""}];
//let sec26=[{name: "" , img: "261.jpg" , rating: 4,prop:" "},{name: "" , img: "262.jpg" , rating:5 ,prop: ""},{name: "" , img: "263.jpg" , rating:4 ,prop: ""},{name: "" , img: "264.jpg" , rating:5 ,prop: ""},{name: "" , img: "265.jpg" , rating:4 ,prop: ""}];
let sec31=[{name: "Reiki Level I, II and Master/Teacher Program" , img: "311.jpg" , rating: 4,prop:"Learn Reiki Levels 1, 2 and Master Level to become a Certified Traditional Usui Reiki Practitioner/Instructor"},{name: "Life Coaching Certificate Course (Beginner to Advanced)" , img: "312.jpg" , rating:5 ,prop: "Learn the transformational Achology Life Coaching process and become a highly skilled, Achology certified Life Coach"},{name: "NLP Practitioner Certificate Course (Beginner to Advanced)" , img: "313.jpg" , rating:4 ,prop: "Undergo this life-transforming training and become an Achology certified Neuro-Linguistic Programming (NLP) Practitioner"},{name: "Animal Reiki Practitioner Certification" , img: "314.jpg" , rating:5 ,prop: "Learn how to use Reiki energy to help animals"},{name: "Crystal Reiki Master/Teacher Certification" , img: "315.jpg" , rating:4 ,prop: "Step into your power and become a Certified Crystal Reiki Master"}];
let sec32=[{name: "Become a SpeedDemon: Productivity Tricks to Have More Time" , img: "321.jpg" , rating: 4,prop:"Learn productivity strategies and easy-to-use tricks to help you get through everyday tasks faster and more efficiently."},{name: "Productivity and Time Management for the Overwhelmed" , img: "322.jpg" , rating:5 ,prop: "A complete productivity and time management course designed to help you reduce your overwhelm and increase your results."},{name: "Productivity Hacks: Free Up Your Time & Live Better" , img: "323.jpg" , rating:4 ,prop: "Stop trying to do it all and focus on what really matters with the help of these practical time-saving strategies."},{name: "Advanced Scripting & Tool Making using Windows PowerShell" , img: "324.jpg" , rating:5 ,prop: "PowerShell | Simplified advanced training on PowerShell with real world problems, PowerShell Automation & PowerShell Lab"},{name: "SUPERHUMAN Productivity 10X: The Secret Skill Of Performance" , img: "325.jpg" , rating:4 ,prop: "Step-by-Step Ultra Productivity: Boost your willpower, habits, motivation, and realize your full productivity potential"}];
let sec33=[{name: "Leadership Skills Mastery Vol. 1: Leadership for 2019" , img: "331.jpg" , rating: 4,prop:"How to Become a Leader and Increase Your Leadership Skills, Influence and Power -Leadership Training, Qualities & Traits"},{name: "Leadership: Leading When You Are Not In Charge!" , img: "332.jpg" , rating:5 ,prop: "Leadership is critical for managers but anyone can lead at anytime. Learn key leadership skills and enhance your career!"},{name: "Fully Accredited Professional Spirituality Coach Diploma" , img: "333.jpg" , rating:4 ,prop: "Fully Accredited Diploma Course - Powerful tools to help yourself or your clients as a Professional Spirituality Coach."},{name: "Influence: Communication Skills for Management & Leadership" , img: "334.jpg" , rating:5 ,prop: "Leadership Communication Skills and People Skills for Persuasive Management Conversations and Influential Team Building"},{name: "Leadership Masterclass" , img: "335.jpg" , rating:4 ,prop: "World-renowned business educator and coach, Dr. Marshall Goldsmith offers practical and proven methods for success."}];
/*let sec34=[{name: "" , img: "341.jpg" , rating: 4,prop:" "},{name: "" , img: "342.jpg" , rating:5 ,prop: ""},{name: "" , img: "343.jpg" , rating:4 ,prop: ""},{name: "" , img: "344.jpg" , rating:5 ,prop: ""},{name: "" , img: "345.jpg" , rating:4 ,prop: ""}];
let sec35=[{name: "" , img: "351.jpg" , rating: 4,prop:" "},{name: "" , img: "352.jpg" , rating:5 ,prop: ""},{name: "" , img: "353.jpg" , rating:4 ,prop: ""},{name: "" , img: "354.jpg" , rating:5 ,prop: ""},{name: "" , img: "355.jpg" , rating:4 ,prop: ""}];
let sec36=[{name: "" , img: "361.jpg" , rating: 4,prop:" "},{name: "" , img: "362.jpg" , rating:5 ,prop: ""},{name: "" , img: "363.jpg" , rating:4 ,prop: ""},{name: "" , img: "364.jpg" , rating:5 ,prop: ""},{name: "" , img: "365.jpg" , rating:4 ,prop: ""}];*/
let sec41=[{name: "Illustrator CC 2020 MasterClass" , img: "411.jpg" , rating: 4,prop:"Bestselling Beginner Course! Use Photoshop, Illustrator, & InDesign for logo design, web design, poster design, and more"},{name: "Illustrator CC 2020 MasterClass" , img: "412.jpg" , rating:5 ,prop: "Master Adobe Illustrator CC with this in-depth training for all levels."}];//{name: "" , img: "413.jpg" , rating:4 ,prop: ""},{name: "" , img: "414.jpg" , rating:5 ,prop: ""},{name: "" , img: "415.jpg" , rating:4 ,prop: ""}];
let sec42=[{name: "Wordpress for Beginners - Master Wordpress Quickly" , img: "421.jpg" , rating: 4,prop:"In 2020, build a beautiful responsive Wordpress site that looks great on all devices. No experience required."},{name: "Web Design for Beginners: Real World Coding in HTML & CSS" , img: "422.jpg" , rating:5 ,prop: "Launch a career as a web designer by learning HTML5, CSS3, responsive design, Sass and more!"}];//{name: "" , img: "423.jpg" , rating:4 ,prop: ""},{name: "" , img: "424.jpg" , rating:5 ,prop: ""},{name: "" , img: "425.jpg" , rating:4 ,prop: ""}];
let sec43=[{name: "The Complete App Design Course - UX, UI and Design Thinking" , img: "431.jpg" , rating: 4,prop:"Learn App Design to Make Beautiful, Lovable Apps "},{name: "User Experience (UX): The Ultimate Guide to Usability and UX" , img: "432.jpg" , rating:5 ,prop: "Get a job in UX and build your user research and UX design skills with this hands-on user experience training course."}];//{name: "" , img: "433.jpg" , rating:4 ,prop: ""},{name: "" , img: "434.jpg" , rating:5 ,prop: ""},{name: "" , img: "435.jpg" , rating:4 ,prop: ""}];
let sec44=[{name: "Pixel art for Video games" , img: "441.jpg" , rating: 4,prop:"The essential course for creating stunning pixel art graphics for video-games or stylish illustrations and designs "}];//{name: "" , img: "443.jpg" , rating:4 ,prop: ""},{name: "" , img: "444.jpg" , rating:5 ,prop: ""},{name: "" , img: "445.jpg" , rating:4 ,prop: ""}];
let sec45=[{name: "Complete Blender Creator: Learn 3D Modelling for Beginners" , img: "451.jpg" , rating: 4,prop:"Use Blender to Create Beautiful 3D models for Video Games, 3D Printing & More. Beginners Level Course "}];//{name: "" , img: "453.jpg" , rating:4 ,prop: ""},{name: "" , img: "454.jpg" , rating:5 ,prop: ""},{name: "" , img: "455.jpg" , rating:4 ,prop: ""}];
let sec46=[{name: "Autodesk Revit - beginner to an intermediate level" , img: "461.jpg" , rating: 4,prop:"Everything you need to know to get started with Revit 2016, 2017, 2018, 2019, 2020 & 2021! "}];//{name: "" , img: "463.jpg" , rating:4 ,prop: ""},{name: "" , img: "464.jpg" , rating:5 ,prop: ""},{name: "" , img: "465.jpg" , rating:4 ,prop: ""}];
/*let sec51=[{name: "" , img: "511.jpg" , rating: 4,prop:" "},{name: "" , img: "512.jpg" , rating:5 ,prop: ""},{name: "" , img: "513.jpg" , rating:4 ,prop: ""},{name: "" , img: "514.jpg" , rating:5 ,prop: ""},{name: "" , img: "515.jpg" , rating:4 ,prop: ""}];
let sec52=[{name: "" , img: "521.jpg" , rating: 4,prop:" "},{name: "" , img: "522.jpg" , rating:5 ,prop: ""},{name: "" , img: "523.jpg" , rating:4 ,prop: ""},{name: "" , img: "524.jpg" , rating:5 ,prop: ""},{name: "" , img: "525.jpg" , rating:4 ,prop: ""}];
let sec53=[{name: "" , img: "531.jpg" , rating: 4,prop:" "},{name: "" , img: "532.jpg" , rating:5 ,prop: ""},{name: "" , img: "533.jpg" , rating:4 ,prop: ""},{name: "" , img: "534.jpg" , rating:5 ,prop: ""},{name: "" , img: "535.jpg" , rating:4 ,prop: ""}];
let sec54=[{name: "" , img: "541.jpg" , rating: 4,prop:" "},{name: "" , img: "542.jpg" , rating:5 ,prop: ""},{name: "" , img: "543.jpg" , rating:4 ,prop: ""},{name: "" , img: "544.jpg" , rating:5 ,prop: ""},{name: "" , img: "545.jpg" , rating:4 ,prop: ""}];
let sec55=[{name: "" , img: "551.jpg" , rating: 4,prop:" "},{name: "" , img: "552.jpg" , rating:5 ,prop: ""},{name: "" , img: "553.jpg" , rating:4 ,prop: ""},{name: "" , img: "554.jpg" , rating:5 ,prop: ""},{name: "" , img: "555.jpg" , rating:4 ,prop: ""}];
let sec56=[{name: "" , img: "561.jpg" , rating: 4,prop:" "},{name: "" , img: "562.jpg" , rating:5 ,prop: ""},{name: "" , img: "563.jpg" , rating:4 ,prop: ""},{name: "" , img: "564.jpg" , rating:5 ,prop: ""},{name: "" , img: "565.jpg" , rating:4 ,prop: ""}];
let sec61=[{name: "" , img: "611.jpg" , rating: 4,prop:" "},{name: "" , img: "612.jpg" , rating:5 ,prop: ""},{name: "" , img: "613.jpg" , rating:4 ,prop: ""},{name: "" , img: "614.jpg" , rating:5 ,prop: ""},{name: "" , img: "615.jpg" , rating:4 ,prop: ""}];
let sec62=[{name: "" , img: "621.jpg" , rating: 4,prop:" "},{name: "" , img: "622.jpg" , rating:5 ,prop: ""},{name: "" , img: "623.jpg" , rating:4 ,prop: ""},{name: "" , img: "624.jpg" , rating:5 ,prop: ""},{name: "" , img: "625.jpg" , rating:4 ,prop: ""}];
let sec63=[{name: "" , img: "631.jpg" , rating: 4,prop:" "},{name: "" , img: "632.jpg" , rating:5 ,prop: ""},{name: "" , img: "633.jpg" , rating:4 ,prop: ""},{name: "" , img: "634.jpg" , rating:5 ,prop: ""},{name: "" , img: "635.jpg" , rating:4 ,prop: ""}];
let sec64=[{name: "" , img: "641.jpg" , rating: 4,prop:" "},{name: "" , img: "642.jpg" , rating:5 ,prop: ""},{name: "" , img: "643.jpg" , rating:4 ,prop: ""},{name: "" , img: "644.jpg" , rating:5 ,prop: ""},{name: "" , img: "645.jpg" , rating:4 ,prop: ""}];
let sec65=[{name: "" , img: "651.jpg" , rating: 4,prop:" "},{name: "" , img: "652.jpg" , rating:5 ,prop: ""},{name: "" , img: "653.jpg" , rating:4 ,prop: ""},{name: "" , img: "654.jpg" , rating:5 ,prop: ""},{name: "" , img: "655.jpg" , rating:4 ,prop: ""}];
let sec66=[{name: "" , img: "661.jpg" , rating: 4,prop:" "},{name: "" , img: "662.jpg" , rating:5 ,prop: ""},{name: "" , img: "663.jpg" , rating:4 ,prop: ""},{name: "" , img: "664.jpg" , rating:5 ,prop: ""},{name: "" , img: "665.jpg" , rating:4 ,prop: ""}];
let sec71=[{name: "" , img: "711.jpg" , rating: 4,prop:" "},{name: "" , img: "712.jpg" , rating:5 ,prop: ""},{name: "" , img: "713.jpg" , rating:4 ,prop: ""},{name: "" , img: "714.jpg" , rating:5 ,prop: ""},{name: "" , img: "715.jpg" , rating:4 ,prop: ""}];
let sec72=[{name: "" , img: "721.jpg" , rating: 4,prop:" "},{name: "" , img: "722.jpg" , rating:5 ,prop: ""},{name: "" , img: "723.jpg" , rating:4 ,prop: ""},{name: "" , img: "724.jpg" , rating:5 ,prop: ""},{name: "" , img: "725.jpg" , rating:4 ,prop: ""}];
let sec73=[{name: "" , img: "731.jpg" , rating: 4,prop:" "},{name: "" , img: "732.jpg" , rating:5 ,prop: ""},{name: "" , img: "733.jpg" , rating:4 ,prop: ""},{name: "" , img: "734.jpg" , rating:5 ,prop: ""},{name: "" , img: "735.jpg" , rating:4 ,prop: ""}];
let sec74=[{name: "" , img: "741.jpg" , rating: 4,prop:" "},{name: "" , img: "742.jpg" , rating:5 ,prop: ""},{name: "" , img: "743.jpg" , rating:4 ,prop: ""},{name: "" , img: "744.jpg" , rating:5 ,prop: ""},{name: "" , img: "745.jpg" , rating:4 ,prop: ""}];
let sec75=[{name: "" , img: "751.jpg" , rating: 4,prop:" "},{name: "" , img: "752.jpg" , rating:5 ,prop: ""},{name: "" , img: "753.jpg" , rating:4 ,prop: ""},{name: "" , img: "754.jpg" , rating:5 ,prop: ""},{name: "" , img: "755.jpg" , rating:4 ,prop: ""}];
let sec76=[{name: "" , img: "761.jpg" , rating: 4,},{name: "" , img: 762.jpg ", ratin" g5 ,},{name: "" , img: 763.jpg , rating":4 ,},{"name: "" , img: 764.jpg , rating:5 ,},{n"ame: """ , img: 765.jpg , rating:4 ,}];  */



let sections=[[sec11,sec12,sec13],[sec21,sec22,sec23],[sec31,sec32,sec33],[sec41,sec42,sec43,sec44,sec45,sec46]]

for(let i=0;i<topics.length;i++)
{
  let addDiv="<div class='first-div' id='section"+(i+1).toString()+"'><h1>"+topics[i]+"</h1></div>";
  $(".content").append(addDiv);
  for(let j=0;j<subtopics[i].length;j++)
  {
    let section="#section"+(i+1).toString();
    let addItemGroups="<div class='second-div' id='section"+(i+1).toString()+(j+1).toString()+"'><h3>"+subtopics[i][j]+"</h3></div>";
    $(section).append(addItemGroups);
    let arr="sec"+(i+1).toString()+(j+1).toString();
    let group="#section"+(i+1).toString()+(j+1).toString();
  //  console.log(arr,arr.length);
    for(let k=0;k<sections[i][j].length;k++)
    {
        let indvidualItemDetails=sections[i][j][k].name;
        let rate="";
        for(let x=0;x<sections[i][j][k].rating;x++)
        {
          rate+="🌟";
        }
          if(sections[i][j][k].prop.length>0)
          {
               indvidualItemDetails=sections[i][j][k].name+"<h5>"+sections[i][j][k].prop+"</h5>";

          }

           let itemDetails="<p><h4>"+indvidualItemDetails+"</h4></p><p>"+rate+"</p>"
        //  console.log(arr[k],arr[k].img);
          let addItem="<div class='third-div row' id='section"+(i+1).toString()+(j+1).toString()+(j+1).toString()+"'><div class='col col-sm-6 col-md-6 col-xsm-12 col-xlg-6 col-lg-6'><img  class='img-item' src='"+sections[i][j][k].img+"' alt='pic'></img></div><div class='col2 col col-sm-6 col-md-6 col-xsm-12 col-xlg-6 col-lg-6' >"+itemDetails+"</div></div>"
          $(group).append(addItem+"<div class='btn btn-primary'>Enroll Now <div>");
          

    }
  }
}
